machina/apps/forum_conversation/forum_attachments/urls.py
"""
    Forum attachments URLs
    ======================

    This module defines URL patterns associated with the django-machina's ``forum_attachments``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumAttachmentsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    attachment_view = get_class('forum_conversation.forum_attachments.views', 'AttachmentView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path('attachment/<int:pk>/', self.attachment_view.as_view(), name='attachment'),
        ]


urlpatterns_factory = ForumAttachmentsURLPatternsFactory()

machina/apps/forum_conversation/forum_polls/urls.py
"""
    Forum polls URLs
    ================

    This module defines URL patterns associated with the django-machina's ``forum_polls``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumPollsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_polls`` application. """

    poll_vote_view = get_class('forum_conversation.forum_polls.views', 'TopicPollVoteView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path('poll/<int:pk>/vote/', self.poll_vote_view.as_view(), name='topic_poll_vote'),
        ]


urlpatterns_factory = ForumPollsURLPatternsFactory()

machina/apps/forum_conversation/urls.py
"""
    Forum conversation URLs
    =======================

    This module defines URL patterns associated with the django-machina's ``forum_conversation``
    application.

"""

from django.urls import include, path

from machina.apps.forum_conversation.forum_attachments.urls import \
    urlpatterns_factory as attachments_urlpatterns_factory
from machina.apps.forum_conversation.forum_polls.urls import \
    urlpatterns_factory as polls_urlpatterns_factory
from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class BaseForumConversationURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_conversation`` application. """

    app_namespace = 'forum_conversation'

    topic_view = get_class('forum_conversation.views', 'TopicView')
    topic_create_view = get_class('forum_conversation.views', 'TopicCreateView')
    topic_update_view = get_class('forum_conversation.views', 'TopicUpdateView')
    post_create_view = get_class('forum_conversation.views', 'PostCreateView')
    post_update_view = get_class('forum_conversation.views', 'PostUpdateView')
    post_delete_view = get_class('forum_conversation.views', 'PostDeleteView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        urlpatterns = super().get_urlpatterns()

        conversation_urlpatterns = [
            path(
                'topic/<str:slug>-<int:pk>/',
                self.topic_view.as_view(),
                name='topic',
            ),
            path('topic/create/', self.topic_create_view.as_view(), name='topic_create'),
            path(
                'topic/<str:slug>-<int:pk>/update/',
                self.topic_update_view.as_view(),
                name='topic_update',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/post/create/',
                self.post_create_view.as_view(),
                name='post_create',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/update/',
                self.post_update_view.as_view(),
                name='post_update',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/delete/',
                self.post_delete_view.as_view(),
                name='post_delete',
            ),
        ]

        urlpatterns += [
            path(
                'forum/<str:forum_slug>-<int:forum_pk>/',
                include(conversation_urlpatterns),
            ),
        ]

        return urlpatterns


class ForumAttachmentsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    attachments_urlpatterns_factory = attachments_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.attachments_urlpatterns_factory.urlpatterns)),
        ]


class ForumPollsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    polls_urlpatterns_factory = polls_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.polls_urlpatterns_factory.urlpatterns)),
        ]


class ForumConversationURLPatternsFactory(
    BaseForumConversationURLPatternsFactory, ForumAttachmentsURLPatternsFactory,
    ForumPollsURLPatternsFactory,
):
    """ Composite class combining conversation views with polls & attachments views. """


urlpatterns_factory = ForumConversationURLPatternsFactory()

machina/apps/forum_member/urls.py
"""
    Forum member URLs
    =================

    This module defines URL patterns associated with the django-machina's ``forum_member``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumMemberURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_member`` application. """

    app_namespace = 'forum_member'

    user_posts_list = get_class('forum_member.views', 'UserPostsView')
    forum_profile_detail_view = get_class('forum_member.views', 'ForumProfileDetailView')
    forum_profile_update_view = get_class('forum_member.views', 'ForumProfileUpdateView')
    topic_subscribe_view = get_class('forum_member.views', 'TopicSubscribeView')
    topic_unsubscribe_view = get_class('forum_member.views', 'TopicUnsubscribeView')
    topic_subscription_list_view = get_class('forum_member.views', 'TopicSubscriptionListView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'profile/edit/',
                self.forum_profile_update_view.as_view(),
                name='profile_update',
            ),
            path(
                'profile/<str:pk>/',
                self.forum_profile_detail_view.as_view(),
                name='profile',
            ),
            path(
                'profile/<str:pk>/posts/',
                self.user_posts_list.as_view(),
                name='user_posts',
            ),
            path(
                'subscriptions/',
                self.topic_subscription_list_view.as_view(),
                name='user_subscriptions',
            ),
            path(
                'topic/<int:pk>/subscribe/',
                self.topic_subscribe_view.as_view(),
                name='topic_subscribe',
            ),
            path(
                'topic/<int:pk>/unsubscribe/',
                self.topic_unsubscribe_view.as_view(),
                name='topic_unsubscribe',
            ),
        ]


urlpatterns_factory = ForumMemberURLPatternsFactory()

machina/apps/forum_moderation/urls.py
"""
    Forum moderation URLs
    =====================

    This module defines URL patterns associated with the django-machina's ``forum_moderation``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumModerationURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_moderation`` application. """

    app_namespace = 'forum_moderation'

    topic_lock_view = get_class('forum_moderation.views', 'TopicLockView')
    topic_unlock_view = get_class('forum_moderation.views', 'TopicUnlockView')
    topic_delete_view = get_class('forum_moderation.views', 'TopicDeleteView')
    topic_move_view = get_class('forum_moderation.views', 'TopicMoveView')
    topic_update_to_normal_topic_view = get_class(
        'forum_moderation.views', 'TopicUpdateToNormalTopicView',
    )
    topic_update_to_sticky_topic_view = get_class(
        'forum_moderation.views', 'TopicUpdateToStickyTopicView',
    )
    topic_update_to_announce_view = get_class('forum_moderation.views', 'TopicUpdateToAnnounceView')
    moderation_queue_list_view = get_class('forum_moderation.views', 'ModerationQueueListView')
    moderation_queue_detail_view = get_class('forum_moderation.views', 'ModerationQueueDetailView')
    post_approve_view = get_class('forum_moderation.views', 'PostApproveView')
    post_disapprove_view = get_class('forum_moderation.views', 'PostDisapproveView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'topic/<str:slug>-<int:pk>/lock/',
                self.topic_lock_view.as_view(),
                name='topic_lock',
            ),
            path(
                'topic/<str:slug>-<int:pk>/unlock/',
                self.topic_unlock_view.as_view(),
                name='topic_unlock',
            ),
            path(
                'topic/<str:slug>-<int:pk>/delete/',
                self.topic_delete_view.as_view(),
                name='topic_delete',
            ),
            path(
                'topic/<str:slug>-<int:pk>/move/',
                self.topic_move_view.as_view(),
                name='topic_move',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/topic/',
                self.topic_update_to_normal_topic_view.as_view(),
                name='topic_update_to_post',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/sticky/',
                self.topic_update_to_sticky_topic_view.as_view(),
                name='topic_update_to_sticky',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/announce/',
                self.topic_update_to_announce_view.as_view(),
                name='topic_update_to_announce',
            ),
            path('queue/', self.moderation_queue_list_view.as_view(), name='queue'),
            path(
                'queue/<int:pk>/',
                self.moderation_queue_detail_view.as_view(),
                name='queued_post',
            ),
            path(
                'queue/<int:pk>/approve/',
                self.post_approve_view.as_view(),
                name='approve_queued_post',
            ),
            path(
                'queue/<int:pk>/disapprove/',
                self.post_disapprove_view.as_view(),
                name='disapprove_queued_post',
            ),
        ]


urlpatterns_factory = ForumModerationURLPatternsFactory()

machina/urls.py
"""
    Machina URLs
    ============

    This module imports all the URLs defined by the forum-related applications.

"""

from django.conf.urls import include, url

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class BoardURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the whole forum application. """

    forum_urlpatterns_factory = get_class('forum.urls', 'urlpatterns_factory')
    conversation_urlpatterns_factory = get_class('forum_conversation.urls', 'urlpatterns_factory')
    feeds_urlpatterns_factory = get_class('forum_feeds.urls', 'urlpatterns_factory')
    member_urlpatterns_factory = get_class('forum_member.urls', 'urlpatterns_factory')
    moderation_urlpatterns_factory = get_class('forum_moderation.urls', 'urlpatterns_factory')
    search_urlpatterns_factory = get_class('forum_search.urls', 'urlpatterns_factory')
    tracking_urlpatterns_factory = get_class('forum_tracking.urls', 'urlpatterns_factory')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            url(r'', include(self.forum_urlpatterns_factory.urlpatterns)),
            url(r'', include(self.conversation_urlpatterns_factory.urlpatterns)),
            url(r'^feeds/', include(self.feeds_urlpatterns_factory.urlpatterns)),
            url(r'^member/', include(self.member_urlpatterns_factory.urlpatterns)),
            url(r'^moderation/', include(self.moderation_urlpatterns_factory.urlpatterns)),
            url(r'^search/', include(self.search_urlpatterns_factory.urlpatterns)),
            url(r'^tracking/', include(self.tracking_urlpatterns_factory.urlpatterns)),
        ]


urlpatterns_factory = BoardURLPatternsFactory()
urlpatterns = urlpatterns_factory.get_urlpatterns()

machina/apps/forum_conversation/forum_attachments/models.py
"""
    Forum attachments models
    ========================

    This module defines models provided by the ``forum_attachments`` application.

"""

from machina.apps.forum_conversation.forum_attachments.abstract_models import AbstractAttachment
from machina.core.db.models import model_factory


Attachment = model_factory(AbstractAttachment)

machina/apps/forum_conversation/forum_polls/models.py
"""
    Forum polls models
    ==================

    This module defines models provided by the ``forum_polls`` application.

"""

from machina.apps.forum_conversation.forum_polls.abstract_models import (
    AbstractTopicPoll, AbstractTopicPollOption, AbstractTopicPollVote
)
from machina.core.db.models import model_factory


TopicPoll = model_factory(AbstractTopicPoll)
TopicPollOption = model_factory(AbstractTopicPollOption)
TopicPollVote = model_factory(AbstractTopicPollVote)

machina/apps/forum_conversation/models.py
"""
    Forum conversation models
    =========================

    This module defines models provided by the ``forum_conversation`` application.

"""

from machina.apps.forum_conversation.abstract_models import AbstractPost, AbstractTopic
from machina.core.db.models import model_factory


Topic = model_factory(AbstractTopic)
Post = model_factory(AbstractPost)

machina/apps/forum_conversation/forum_attachments/forms.py
"""
    Forum attachments forms
    =======================

    This module defines forms provided by the ``forum_attachments`` application.

"""

from django import forms
from django.forms.models import BaseModelFormSet, modelformset_factory

from machina.conf import settings as machina_settings
from machina.core.db.models import get_model


Attachment = get_model('forum_attachments', 'Attachment')


class AttachmentForm(forms.ModelForm):
    """ Allows to upload forum attachments. """

    class Meta:
        model = Attachment
        fields = ['file', 'comment', ]


class BaseAttachmentFormset(BaseModelFormSet):
    """ Base class allowing to define forum attachment formsets. """

    def __init__(self, *args, **kwargs):
        self.post = kwargs.pop('post', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True, **kwargs):
        """ Saves the considered instances. """
        if self.post:
            for form in self.forms:
                form.instance.post = self.post
        super().save(commit)


AttachmentFormset = modelformset_factory(
    Attachment, AttachmentForm,
    formset=BaseAttachmentFormset,
    can_delete=True, extra=1,
    max_num=machina_settings.ATTACHMENT_MAX_FILES_PER_POST,
    validate_max=True,
)

machina/apps/forum_conversation/forum_attachments/views.py
"""
    Forum attachments views
    =======================

    This module defines views provided by the ``forum_attachments`` application.

"""

import mimetypes
import os

from django.http import HttpResponse
from django.views.generic import DetailView

from machina.core.db.models import get_model
from machina.core.loading import get_class


Attachment = get_model('forum_attachments', 'Attachment')

PermissionRequiredMixin = get_class('forum_permission.viewmixins', 'PermissionRequiredMixin')


class AttachmentView(PermissionRequiredMixin, DetailView):
    """ Allows to retrieve a forum attachment. """

    model = Attachment

    def render_to_response(self, context, **response_kwargs):
        """ Generates the appropriate response. """
        filename = os.path.basename(self.object.file.name)

        # Try to guess the content type of the given file
        content_type, _ = mimetypes.guess_type(self.object.file.name)
        if not content_type:
            content_type = 'text/plain'

        response = HttpResponse(self.object.file, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename={}'.format(filename)

        return response

    def get_controlled_object(self):
        """ Returns the controlled object. """
        return self.get_object().post.topic.forum

    def perform_permissions_check(self, user, obj, perms):
        """ Performs the permission check. """
        return self.request.forum_permission_handler.can_download_files(obj, user)

machina/templates/machina/forum_conversation/partials/post_form.html
{% load i18n %}

{% if post_form.non_field_errors %}
{% for error in post_form.non_field_errors %}
<div class="alert alert-danger">
  <i class="icon-exclamation-sign"></i> {{ error }}
</div>
{% endfor %}
{% endif %}
{% include "partials/form_field.html" with field=post_form.subject %}
{% include "partials/form_field.html" with field=post_form.content %}
{% if post_form.username %}
    {% include "partials/form_field.html" with field=post_form.username %}
{% endif %}
{% if post_form.update_reason %}
    {% include "partials/form_field.html" with field=post_form.update_reason %}
{% endif %}
<!-- Sub "forms" tabs -->
{% if attachment_formset %}
<ul class="nav nav-tabs nav-justified">
  <li class="nav-item"><a href="#options" class="nav-link active" data-toggle="tab">{% trans "Options" %}</a></li>
  <li class="nav-item"><a href="#attachments" class="nav-link" data-toggle="tab">{% trans "Attachments" %}</a></li>
</ul>
{% endif %}
<!-- Sub "forms" panes -->
<div class="tab-content">
  <div class="tab-pane active" id="options">
    <div class="form-group">
      <br />
      <div class="row">
        <div class="col-md-12">
          {% with field=post_form.enable_signature %}
          <div class="checkbox">
            <label for="{{ field.auto_id }}">
              {{ field }}
              {{ field.label }}
            </label>
          </div>
          {% endwith %}
          {% if post_form.lock_topic %}
          {% with field=post_form.lock_topic %}
          <div class="checkbox">
            <label for="{{ field.auto_id }}">
              {{ field }}
              {{ field.label }}
            </label>
          </div>
          {% endwith %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% if attachment_formset %}
  <div class="tab-pane" id="attachments">
    <div class="form-group">
      <br />
      <div class="row">
        <div id="attachment_formset" class="col-md-12">
           <p class="lead attachments-title">{% trans "Attachments" %}</p>
          {% include "forum_conversation/forum_attachments/attachment_formset.html" %}
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>

machina/templates/machina/forum_conversation/partials/topic_detail_actions.html
{% load i18n %}
{% load forum_permission_tags %}

{% get_permission 'can_add_post' topic request.user as user_can_add_post %}
{% get_permission 'can_subscribe_to_topic' topic request.user as user_can_subscribe_to_topic %}
{% get_permission 'can_unsubscribe_from_topic' topic request.user as user_can_unsubscribe_from_topic %}
{% get_permission 'can_lock_topics' topic.forum request.user as user_can_lock_topics %}
{% get_permission 'can_move_topics' topic.forum request.user as user_can_move_topics %}
{% get_permission 'can_delete_topics' topic.forum request.user as user_can_delete_topics %}
{% get_permission 'can_update_topics_to_normal_topics' topic.forum request.user as user_can_change_to_normal_topics %}
{% get_permission 'can_update_topics_to_sticky_topics' topic.forum request.user as user_can_change_to_sticky_topics %}
{% get_permission 'can_update_topics_to_announces' topic.forum request.user as user_can_change_to_announces %}

{% if user_can_add_post %}
<a href="{% url 'forum_conversation:post_create' forum.slug forum.pk topic.slug topic.pk %}" class="btn btn-primary btn-sm"><i class="fa fa-comment fa-lg"></i>&nbsp;{% trans "Post reply" %}</a>
{% endif %}
{% if user_can_subscribe_to_topic %}
<a href="{% url 'forum_member:topic_subscribe' topic.pk %}" class="btn btn-info btn-sm btn-subscription"><i class="fas fa-check">&nbsp;</i>{% trans "Subscribe" %}</a>
{% elif user_can_unsubscribe_from_topic %}
<a href="{% url 'forum_member:topic_unsubscribe' topic.pk %}" class="btn btn-info btn-sm btn-subscription"><i class="fas fa-times">&nbsp;</i>{% trans "Unsubscribe" %}</a>
{% endif %}
{% if user_can_lock_topics and not topic.is_locked or user_can_move_topics or user_can_delete_topics %}
<div class="btn-group moderation-dropdown">
  <button id="id_dropdown_moderation_menu_button" class="btn btn-warning btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-gavel">&nbsp;&nbsp;</i><span class="caret"></span></button>
  <div class="dropdown-menu" aria-labelledby="id_dropdown_moderation_menu_button" style="min-width:13rem;">
    {% if user_can_lock_topics and not topic.is_locked %}<a href="{% url 'forum_moderation:topic_lock' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Lock topic" %}</a>{% endif %}
    {% if user_can_lock_topics and topic.is_locked %}<a href="{% url 'forum_moderation:topic_unlock' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Unlock topic" %}</a>{% endif %}
    {% if user_can_delete_topics %}<a href="{% url 'forum_moderation:topic_delete' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Delete topic" %}</a>{% endif %}
    {% if user_can_move_topics %}<a href="{% url 'forum_moderation:topic_move' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Move topic" %}</a>{% endif %}
    {% if topic.is_topic %}
    {% if user_can_change_to_sticky_topics %}<a href="{% url 'forum_moderation:topic_update_to_sticky' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Change to sticky topic" %}</a>{% endif %}
    {% if user_can_change_to_announces %}<a href="{% url 'forum_moderation:topic_update_to_announce' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Change to announce" %}</a>{% endif %}
    {% elif topic.is_sticky %}
    {% if user_can_change_to_normal_topics %}<a href="{% url 'forum_moderation:topic_update_to_post' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Change to standard topic" %}</a>{% endif %}
    {% if user_can_change_to_announces %}<a href="{% url 'forum_moderation:topic_update_to_announce' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Change to announce" %}</a>{% endif %}
    {% elif topic.is_announce %}
    {% if user_can_change_to_normal_topics %}<a href="{% url 'forum_moderation:topic_update_to_post' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Change to standard topic" %}</a>{% endif %}
    {% if user_can_change_to_sticky_topics %}<a href="{% url 'forum_moderation:topic_update_to_sticky' slug=topic.slug pk=topic.pk %}" class="dropdown-item">{% trans "Change to sticky topic" %}</a>{% endif %}
    {% endif %}
  </div>
</div>
{% endif %}

machina/templates/machina/forum_conversation/partials/topic_form.html
{% load i18n %}

<form method="post" action="." class="form" enctype="multipart/form-data" novalidate>{% csrf_token %}
  {% for error in post_form.non_field_errors %}
  <div class="alert alert-danger">
    <i class="icon-exclamation-sign"></i> {{ error }}
  </div>
  {% endfor %}

  {% include "partials/form_field.html" with field=post_form.subject %}
  {% include "partials/form_field.html" with field=post_form.content %}
  {% if post_form.username %}
    {% include "partials/form_field.html" with field=post_form.username %}
  {% endif %}
  {% if post_form.update_reason %}
    {% include "partials/form_field.html" with field=post_form.update_reason %}
  {% endif %}

  <!-- Sub "forms" tabs -->
  {% if poll_option_formset or attachment_formset %}
  <ul class="nav nav-tabs nav-justified">
    <li class="nav-item"><a href="#options" class="nav-link active" data-toggle="tab">{% trans "Options" %}</a></li>
    {% if poll_option_formset %}<li class="nav-item"><a href="#poll" class="nav-link" data-toggle="tab">{% trans "Poll" %}</a></li>{% endif %}
    {% if attachment_formset %}<li class="nav-item"><a href="#attachments" class="nav-link" data-toggle="tab">{% trans "Attachments" %}</a></li>{% endif %}
  </ul>
  {% endif %}

  <!-- Sub "forms" panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="options">
      <div class="form-group">
        <br />
        <div class="row">
          <div class="col-md-12">
            {% include "partials/form_field.html" with field=post_form.topic_type %}
            {% with field=post_form.enable_signature %}
            <div class="checkbox">
              <label for="{{ field.auto_id }}">
                {{ field }}
                {{ field.label }}
              </label>
            </div>
            {% endwith %}
            {% if post_form.lock_topic %}
            {% with field=post_form.lock_topic %}
            <div class="checkbox">
              <label for="{{ field.auto_id }}">
                {{ field }}
                {{ field.label }}
              </label>
            </div>
            {% endwith %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% if poll_option_formset %}
    <div class="tab-pane" id="poll">
      <div class="form-group">
        <br />
        {% if poll_options_validated and poll_option_formset.non_form_errors %}<div class="alert alert-danger">{{ poll_option_formset.non_form_errors|striptags }}</div>{% endif %}
        <div class="row">
          <div class="col-md-6">
            {% include "partials/form_field.html" with field=post_form.poll_question %}
            {% include "partials/form_field.html" with field=post_form.poll_max_options %}
            {% include "partials/form_field.html" with field=post_form.poll_duration %}
            <div{% if post_form.poll_user_changes.errors %} class="has-error"{% endif %}>
              <div class="checkbox">
                <label for="{{ post_form.poll_user_changes.auto_id }}">
                  {{ post_form.poll_user_changes }}
                  {{ post_form.poll_user_changes.label }}
                </label>
              </div>
            </div>
          </div>
          <div id="poll_formset" class="col-md-6">
            {% include "forum_conversation/forum_polls/poll_option_formset.html" %}
          </div>
        </div>
      </div>
    </div>
    {% endif %}
    {% if attachment_formset %}
    <div class="tab-pane" id="attachments">
      <div class="form-group">
        <br />
        <div class="row">
          <div id="attachment_formset" class="col-md-12">
            {% include "forum_conversation/forum_attachments/attachment_formset.html" %}
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>

  <div class="form-actions">
    <input type="submit" name="preview" class="btn btn-large btn-default" value="{% trans "Preview" %}" />&nbsp;
    <input type="submit" class="btn btn-large btn-primary" value="{% trans "Submit" %}" />
  </div>
</form>