machina/apps/forum_conversation/forum_attachments/urls.py
"""
    Forum attachments URLs
    ======================

    This module defines URL patterns associated with the django-machina's ``forum_attachments``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumAttachmentsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    attachment_view = get_class('forum_conversation.forum_attachments.views', 'AttachmentView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path('attachment/<int:pk>/', self.attachment_view.as_view(), name='attachment'),
        ]


urlpatterns_factory = ForumAttachmentsURLPatternsFactory()

machina/apps/forum_conversation/forum_polls/urls.py
"""
    Forum polls URLs
    ================

    This module defines URL patterns associated with the django-machina's ``forum_polls``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumPollsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_polls`` application. """

    poll_vote_view = get_class('forum_conversation.forum_polls.views', 'TopicPollVoteView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path('poll/<int:pk>/vote/', self.poll_vote_view.as_view(), name='topic_poll_vote'),
        ]


urlpatterns_factory = ForumPollsURLPatternsFactory()

machina/apps/forum_conversation/urls.py
"""
    Forum conversation URLs
    =======================

    This module defines URL patterns associated with the django-machina's ``forum_conversation``
    application.

"""

from django.urls import include, path

from machina.apps.forum_conversation.forum_attachments.urls import \
    urlpatterns_factory as attachments_urlpatterns_factory
from machina.apps.forum_conversation.forum_polls.urls import \
    urlpatterns_factory as polls_urlpatterns_factory
from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class BaseForumConversationURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_conversation`` application. """

    app_namespace = 'forum_conversation'

    topic_view = get_class('forum_conversation.views', 'TopicView')
    topic_create_view = get_class('forum_conversation.views', 'TopicCreateView')
    topic_update_view = get_class('forum_conversation.views', 'TopicUpdateView')
    post_create_view = get_class('forum_conversation.views', 'PostCreateView')
    post_update_view = get_class('forum_conversation.views', 'PostUpdateView')
    post_delete_view = get_class('forum_conversation.views', 'PostDeleteView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        urlpatterns = super().get_urlpatterns()

        conversation_urlpatterns = [
            path(
                'topic/<str:slug>-<int:pk>/',
                self.topic_view.as_view(),
                name='topic',
            ),
            path('topic/create/', self.topic_create_view.as_view(), name='topic_create'),
            path(
                'topic/<str:slug>-<int:pk>/update/',
                self.topic_update_view.as_view(),
                name='topic_update',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/post/create/',
                self.post_create_view.as_view(),
                name='post_create',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/update/',
                self.post_update_view.as_view(),
                name='post_update',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/delete/',
                self.post_delete_view.as_view(),
                name='post_delete',
            ),
        ]

        urlpatterns += [
            path(
                'forum/<str:forum_slug>-<int:forum_pk>/',
                include(conversation_urlpatterns),
            ),
        ]

        return urlpatterns


class ForumAttachmentsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    attachments_urlpatterns_factory = attachments_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.attachments_urlpatterns_factory.urlpatterns)),
        ]


class ForumPollsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    polls_urlpatterns_factory = polls_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.polls_urlpatterns_factory.urlpatterns)),
        ]


class ForumConversationURLPatternsFactory(
    BaseForumConversationURLPatternsFactory, ForumAttachmentsURLPatternsFactory,
    ForumPollsURLPatternsFactory,
):
    """ Composite class combining conversation views with polls & attachments views. """


urlpatterns_factory = ForumConversationURLPatternsFactory()

machina/apps/forum_member/urls.py
"""
    Forum member URLs
    =================

    This module defines URL patterns associated with the django-machina's ``forum_member``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumMemberURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_member`` application. """

    app_namespace = 'forum_member'

    user_posts_list = get_class('forum_member.views', 'UserPostsView')
    forum_profile_detail_view = get_class('forum_member.views', 'ForumProfileDetailView')
    forum_profile_update_view = get_class('forum_member.views', 'ForumProfileUpdateView')
    topic_subscribe_view = get_class('forum_member.views', 'TopicSubscribeView')
    topic_unsubscribe_view = get_class('forum_member.views', 'TopicUnsubscribeView')
    topic_subscription_list_view = get_class('forum_member.views', 'TopicSubscriptionListView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'profile/edit/',
                self.forum_profile_update_view.as_view(),
                name='profile_update',
            ),
            path(
                'profile/<str:pk>/',
                self.forum_profile_detail_view.as_view(),
                name='profile',
            ),
            path(
                'profile/<str:pk>/posts/',
                self.user_posts_list.as_view(),
                name='user_posts',
            ),
            path(
                'subscriptions/',
                self.topic_subscription_list_view.as_view(),
                name='user_subscriptions',
            ),
            path(
                'topic/<int:pk>/subscribe/',
                self.topic_subscribe_view.as_view(),
                name='topic_subscribe',
            ),
            path(
                'topic/<int:pk>/unsubscribe/',
                self.topic_unsubscribe_view.as_view(),
                name='topic_unsubscribe',
            ),
        ]


urlpatterns_factory = ForumMemberURLPatternsFactory()

machina/urls.py
"""
    Machina URLs
    ============

    This module imports all the URLs defined by the forum-related applications.

"""

from django.conf.urls import include, url

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class BoardURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the whole forum application. """

    forum_urlpatterns_factory = get_class('forum.urls', 'urlpatterns_factory')
    conversation_urlpatterns_factory = get_class('forum_conversation.urls', 'urlpatterns_factory')
    feeds_urlpatterns_factory = get_class('forum_feeds.urls', 'urlpatterns_factory')
    member_urlpatterns_factory = get_class('forum_member.urls', 'urlpatterns_factory')
    moderation_urlpatterns_factory = get_class('forum_moderation.urls', 'urlpatterns_factory')
    search_urlpatterns_factory = get_class('forum_search.urls', 'urlpatterns_factory')
    tracking_urlpatterns_factory = get_class('forum_tracking.urls', 'urlpatterns_factory')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            url(r'', include(self.forum_urlpatterns_factory.urlpatterns)),
            url(r'', include(self.conversation_urlpatterns_factory.urlpatterns)),
            url(r'^feeds/', include(self.feeds_urlpatterns_factory.urlpatterns)),
            url(r'^member/', include(self.member_urlpatterns_factory.urlpatterns)),
            url(r'^moderation/', include(self.moderation_urlpatterns_factory.urlpatterns)),
            url(r'^search/', include(self.search_urlpatterns_factory.urlpatterns)),
            url(r'^tracking/', include(self.tracking_urlpatterns_factory.urlpatterns)),
        ]


urlpatterns_factory = BoardURLPatternsFactory()
urlpatterns = urlpatterns_factory.get_urlpatterns()

machina/apps/forum_conversation/forum_attachments/models.py
"""
    Forum attachments models
    ========================

    This module defines models provided by the ``forum_attachments`` application.

"""

from machina.apps.forum_conversation.forum_attachments.abstract_models import AbstractAttachment
from machina.core.db.models import model_factory


Attachment = model_factory(AbstractAttachment)

machina/apps/forum_conversation/forum_polls/models.py
"""
    Forum polls models
    ==================

    This module defines models provided by the ``forum_polls`` application.

"""

from machina.apps.forum_conversation.forum_polls.abstract_models import (
    AbstractTopicPoll, AbstractTopicPollOption, AbstractTopicPollVote
)
from machina.core.db.models import model_factory


TopicPoll = model_factory(AbstractTopicPoll)
TopicPollOption = model_factory(AbstractTopicPollOption)
TopicPollVote = model_factory(AbstractTopicPollVote)

machina/apps/forum_conversation/models.py
"""
    Forum conversation models
    =========================

    This module defines models provided by the ``forum_conversation`` application.

"""

from machina.apps.forum_conversation.abstract_models import AbstractPost, AbstractTopic
from machina.core.db.models import model_factory


Topic = model_factory(AbstractTopic)
Post = model_factory(AbstractPost)

machina/apps/forum_conversation/forum_attachments/forms.py
"""
    Forum attachments forms
    =======================

    This module defines forms provided by the ``forum_attachments`` application.

"""

from django import forms
from django.forms.models import BaseModelFormSet, modelformset_factory

from machina.conf import settings as machina_settings
from machina.core.db.models import get_model


Attachment = get_model('forum_attachments', 'Attachment')


class AttachmentForm(forms.ModelForm):
    """ Allows to upload forum attachments. """

    class Meta:
        model = Attachment
        fields = ['file', 'comment', ]


class BaseAttachmentFormset(BaseModelFormSet):
    """ Base class allowing to define forum attachment formsets. """

    def __init__(self, *args, **kwargs):
        self.post = kwargs.pop('post', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True, **kwargs):
        """ Saves the considered instances. """
        if self.post:
            for form in self.forms:
                form.instance.post = self.post
        super().save(commit)


AttachmentFormset = modelformset_factory(
    Attachment, AttachmentForm,
    formset=BaseAttachmentFormset,
    can_delete=True, extra=1,
    max_num=machina_settings.ATTACHMENT_MAX_FILES_PER_POST,
    validate_max=True,
)

machina/apps/forum_conversation/forum_attachments/views.py
"""
    Forum attachments views
    =======================

    This module defines views provided by the ``forum_attachments`` application.

"""

import mimetypes
import os

from django.http import HttpResponse
from django.views.generic import DetailView

from machina.core.db.models import get_model
from machina.core.loading import get_class


Attachment = get_model('forum_attachments', 'Attachment')

PermissionRequiredMixin = get_class('forum_permission.viewmixins', 'PermissionRequiredMixin')


class AttachmentView(PermissionRequiredMixin, DetailView):
    """ Allows to retrieve a forum attachment. """

    model = Attachment

    def render_to_response(self, context, **response_kwargs):
        """ Generates the appropriate response. """
        filename = os.path.basename(self.object.file.name)

        # Try to guess the content type of the given file
        content_type, _ = mimetypes.guess_type(self.object.file.name)
        if not content_type:
            content_type = 'text/plain'

        response = HttpResponse(self.object.file, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename={}'.format(filename)

        return response

    def get_controlled_object(self):
        """ Returns the controlled object. """
        return self.get_object().post.topic.forum

    def perform_permissions_check(self, user, obj, perms):
        """ Performs the permission check. """
        return self.request.forum_permission_handler.can_download_files(obj, user)

machina/apps/forum_conversation/forum_polls/views.py
"""
    Forum polls views
    =================

    This module defines views provided by the ``forum_polls`` application.

"""

from django.contrib import messages
from django.forms.forms import NON_FIELD_ERRORS
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView
from django.views.generic.edit import ModelFormMixin

from machina.core.db.models import get_model
from machina.core.loading import get_class


TopicPoll = get_model('forum_polls', 'TopicPoll')
TopicPollVote = get_model('forum_polls', 'TopicPollVote')

TopicPollVoteForm = get_class('forum_polls.forms', 'TopicPollVoteForm')

PermissionRequiredMixin = get_class('forum_permission.viewmixins', 'PermissionRequiredMixin')


class TopicPollVoteView(PermissionRequiredMixin, UpdateView):
    """ Allows to vote in polls. """

    form_class = TopicPollVoteForm
    http_method_names = ['post', ]
    model = TopicPoll

    def get_form_kwargs(self):
        """ Returns the keyword arguments to provide tp the associated form. """
        kwargs = super(ModelFormMixin, self).get_form_kwargs()
        kwargs['poll'] = self.object
        return kwargs

    def form_valid(self, form):
        """ Handles a valid form. """
        user_kwargs = (
            {'voter': self.request.user}
            if self.request.user.is_authenticated
            else {'anonymous_key': self.request.user.forum_key}
        )

        if self.object.user_changes:
            # If user changes are allowed for this poll, all the poll associated with the current
            # user must be deleted.
            TopicPollVote.objects.filter(poll_option__poll=self.object, **user_kwargs).delete()

        options = form.cleaned_data['options']
        for option in options:
            TopicPollVote.objects.create(poll_option=option, **user_kwargs)

        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        """ Handles an invalid form. """
        messages.error(self.request, form.errors[NON_FIELD_ERRORS])
        return redirect(
            reverse(
                'forum_conversation:topic',
                kwargs={
                    'forum_slug': self.object.topic.forum.slug,
                    'forum_pk': self.object.topic.forum.pk,
                    'slug': self.object.topic.slug,
                    'pk': self.object.topic.pk
                },
            ),
        )

    def get_success_url(self):
        """ Returns the success URL to redirect the user to. """
        messages.success(self.request, _('Your vote has been cast.'))
        return reverse(
            'forum_conversation:topic',
            kwargs={
                'forum_slug': self.object.topic.forum.slug,
                'forum_pk': self.object.topic.forum.pk,
                'slug': self.object.topic.slug,
                'pk': self.object.topic.pk,
            },
        )

    def get_controlled_object(self):
        """ Returns the controlled object. """
        return self.get_object()

    def perform_permissions_check(self, user, obj, perms):
        """ Performs the permission check. """
        return self.request.forum_permission_handler.can_vote_in_poll(obj, user)

machina/templates/machina/forum_conversation/post_create.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_conversation_tags %}
{% load forum_member_tags %}

{% block sub_title %}{% trans "Post a reply" %}{% endblock sub_title %}

{% block content %}
<div class="row">
  <div class="col-12">
    <h1>{{ topic.subject }}</h1>
  </div>
</div>
{% if preview %}
  {% include "forum_conversation/post_preview.html" %}
{% endif %}
<div class="row">
  <div class="col-12">
    <div class="card post-edit">
      <div class="card-header">
        <h3 class="m-0 h5 card-title">{% trans "Post a reply" %}</h3>
      </div>
      <div class="card-body">
        <form method="post" action="." class="form" enctype="multipart/form-data" novalidate>{% csrf_token %}
          {% include "forum_conversation/partials/post_form.html" %}
          <div class="form-actions">
            <input type="submit" name="preview" class="btn btn-large btn-default" value="{% trans "Preview" %}" />&nbsp;
            <input type="submit" class="btn btn-large btn-primary" value="{% trans "Submit" %}" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="mt-3 row">
  <div class="col-12">
    <div class="card topic-review">
      <div class="card-header">
        <h3 class="m-0 h5 card-title">{% trans "Topic review" %}&nbsp;&ndash;&nbsp;{{ topic.subject }}</h3>
      </div>
      <div class="card-body">
        {% for post in previous_posts %}
        <div class="row post-review">
          <div class="col-md-10 post-content-wrapper">
            <h4 class="subject">{{ post.subject }}</h4>
            <p><small class="text-muted">
            {% spaceless %}
              <i class="fa fa-clock-o"></i>&nbsp;
              {% if post.poster %}
                {% url 'forum_member:profile' post.poster_id as poster_url %}
                {% blocktrans trimmed with poster_url=poster_url username=post.poster|forum_member_display_name creation_date=post.created %}
                  By: <a href="{{ poster_url }}">{{ username }}</a> on {{ creation_date }}
                {% endblocktrans %}
              {% else %}
                {% blocktrans trimmed with poster_username=post.username creation_date=post.created %}
                  By: {{ poster_username }} on {{ creation_date }}
                {% endblocktrans %}
              {% endif %}
            {% endspaceless %}
            </small></p>
            <div class="post-content">
              {{ post.content.rendered }}
            </div>
            {% include "forum_conversation/forum_attachments/attachments_detail.html" %}
          </div>
          <div class="col-md-2 post-sidebar">
            <div class="username">{% if post.poster %}<a href="{% url 'forum_member:profile' post.poster_id %}"><b>{{ post.poster|forum_member_display_name }}</b></a>{% else %}<b>{{ post.username }}</b>{% endif %}</div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block onbodyload %}
  machina.attachment.init();
{% endblock onbodyload %}

{% block extra_css %}
  {{ post_form.media.css }}
{% endblock extra_css %}

{% block extra_js %}
  {{ post_form.media.js }}
{% endblock extra_js %}

machina/templates/machina/forum_conversation/post_delete.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_conversation_tags %}

{% block sub_title %}{% trans "Delete post" %}{% endblock sub_title %}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card post-delete">
      <div class="card-header">
        <h3 class="m-0 card-title h5">{% trans "Delete post" %}</h3>
      </div>
      <div class="card-body">
        <div class="mb-3 warning-message">{% trans "Are you sure you want to delete this post?" %}</div>
        <form action="" method="post">{% csrf_token %}
          <input type="hidden" name="post" value="yes" />
          <button role="submit" class="btn btn-warning">{% trans "Yes, I'm sure" %}</button>
          <a href="{% url 'forum_conversation:topic' topic.forum.slug topic.forum.pk topic.slug topic.pk %}" class="btn btn-secondary">{% trans "No, take me back" %}</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

machina/templates/machina/forum_conversation/post_preview.html
{% load i18n %}
{% load forum_markup_tags %}

<div class="mb-3 row preview">
  <div class="col-12">
    <div class="card post post-preview">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12 post-content-wrapper">
            <h4 class="m-0 subject">{% trans "Preview:" %}&nbsp;{{ post_form.subject.value }}</h4>
            <hr />
            <div class="post-content">
              {{ post_form.content.value|safe|rendered }}
            </div>
            {% include "forum_conversation/forum_attachments/attachments_preview.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

machina/templates/machina/forum_conversation/post_update.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_conversation_tags %}

{% block sub_title %}{% trans "Edit post" %}{% endblock sub_title %}

{% block content %}
<div class="row">
  <div class="col-12">
    <h1>{{ topic.subject }}</h1>
  </div>
</div>
{% if preview %}
  {% include "forum_conversation/post_preview.html" %}
{% endif %}
<div class="row">
  <div class="col-12">
    <div class="card post-edit">
      <div class="card-header">
        <h3 class="m-0 h5 card-title">{% trans "Edit post" %}</h3>
      </div>
      <div class="card-body">
        <form method="post" action="." class="form" enctype="multipart/form-data" novalidate>{% csrf_token %}
          {% include "forum_conversation/partials/post_form.html" %}
          <div class="form-actions">
            <input type="submit" name="preview" class="btn btn-large btn-default" value="{% trans "Preview" %}" />&nbsp;
            <input type="submit" class="btn btn-large btn-primary" value="{% trans "Submit" %}" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block onbodyload %}
  machina.attachment.init();
{% endblock onbodyload %}

{% block extra_css %}
  {{ post_form.media.css }}
{% endblock extra_css %}

{% block extra_js %}
  {{ post_form.media.js }}
{% endblock extra_js %}

machina/templates/machina/forum_conversation/topic_detail.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_conversation_tags %}
{% load forum_member_tags %}
{% load forum_permission_tags %}

{% block sub_title %}{{ topic.subject }}{% endblock sub_title %}

{% block content %}
<div class="row"><div class="col-12"><h1>{{ topic.subject }}</h1></div></div>
<div class="row">
  <div class="col-12 col-md-4 topic-actions-block">
  {% include "forum_conversation/partials/topic_detail_actions.html" %}
  </div>
  <div class="col-12 col-md-8 pagination-block">
  {% with "pagination-sm justify-content-end" as pagination_size %}
  {% include "partials/pagination.html" %}
  {% endwith %}
  </div>
</div>
<div class="row">
  <div class="col-12">
  {% for post in posts %}
    {% if forloop.first and post.is_topic_head and poll %}
    {% include "forum_conversation/forum_polls/poll_detail.html" %}
    {% endif %}
    <div id="{{ post.id }}" class="my-3 card post">
      <div class="card-body">
        <div class="row">
          <div class="col-md-10 post-content-wrapper">
            <div class="float-right post-controls">
              {% get_permission 'can_edit_post' post request.user as user_can_edit_post %}
              {% if user_can_edit_post %}
              <a href="{% if post.is_topic_head %}{% url 'forum_conversation:topic_update' forum.slug forum.pk topic.slug topic.pk %}{% else %}{% url 'forum_conversation:post_update' forum.slug forum.pk topic.slug topic.pk post.pk %}{% endif %}" class="btn btn-warning btn-sm" title="{% trans "Edit" %}"><i class="fas fa-edit"></i>&nbsp;{% trans "Edit" %}</a>
              {% endif %}
              {% get_permission 'can_delete_post' post request.user as user_can_delete_post %}
              {% if user_can_delete_post %}
              <a href="{% url 'forum_conversation:post_delete' forum.slug forum.pk topic.slug topic.pk post.pk %}" class="btn btn-danger btn-sm" title="{% trans "Delete" %}"><i class="fas fa-times"></i></a>
              {% endif %}
            </div>
              {% spaceless %}
              <h4 class="m-0 subject">
                {{ post.subject }}
                &nbsp;<a href="{% url 'forum_conversation:topic' forum.slug forum.pk topic.slug topic.pk %}?post={{ post.pk }}#{{ post.pk }}">&#182;</a>
              </h4>
              {% endspaceless %}
              <p>
                <small class="text-muted">
                {% spaceless %}
                <i class="fas fa-clock"></i>&nbsp;
                {% if post.poster %}
                {% url 'forum_member:profile' post.poster_id as poster_url %}
                {% blocktrans trimmed with poster_url=poster_url username=post.poster|forum_member_display_name creation_date=post.created %}
                  By: <a href="{{ poster_url }}">{{ username }}</a> on {{ creation_date }}
                {% endblocktrans %}
                {% else %}
                {% blocktrans trimmed with poster_username=post.username creation_date=post.created %}
                  By: {{ poster_username }} on {{ creation_date }}
                {% endblocktrans %}
                {% endif %}
                {% endspaceless %}
                </small>
              </p>
              <div class="post-content">
                {{ post.content.rendered }}
              </div>
              {% include "forum_conversation/forum_attachments/attachments_detail.html" %}
              {% if post.enable_signature and post.poster.forum_profile.signature %}
              <div class="post-signature">
                {{ post.poster.forum_profile.signature.rendered }}
              </div>
              {% endif %}
              {% if post.updates_count %}
              <div class="mt-4 edit-info">
                <small class="text-muted">
                  <i class="fas fa-edit"></i>&nbsp;{% if post.updated_by %}{% trans "Last edited by:" %}&nbsp;<a href="{% url 'forum_member:profile' post.updated_by_id %}">{{ post.updated_by|forum_member_display_name }}</a>&nbsp;{% else %}{% trans "Updated" %}&nbsp;{% endif %}{% trans "on" %}&nbsp;{{ post.updated }}, {% blocktrans count counter=post.updates_count %}edited {{counter }} time in total.{% plural %}edited {{counter }} times in total.{% endblocktrans %}
                </small>
                {% if post.update_reason %}
                <br />
                <small class="text-muted">
                  <b>{% trans "Reason:" %}</b>&nbsp;{{ post.update_reason }}
                </small>
                {% endif %}
              </div>
              {% endif %}
          </div>
          <div class="col-md-2 d-none d-md-block post-sidebar">
            {% if post.poster %}
            <div class="avatar">
              <a href="{% url 'forum_member:profile' post.poster_id %}">
                {% include "partials/avatar.html" with profile=post.poster.forum_profile show_placeholder=True %}
              </a>
            </div>
            <div class="username"><a href="{% url 'forum_member:profile' post.poster_id %}"><b>{{ post.poster|forum_member_display_name }}</b></a></div>
            <div class="posts-count text-muted"><b>{% trans "Posts:" %}</b>&nbsp;{{ post.poster.forum_profile.posts_count }}</div>
            {% else %}
            <div class="username"><b>{{ post.username }}</b></div>
            <div class="username text-muted">{% trans "Anonymous user" %}</div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
<div class="row">
  <div class="col-6 col-md-4 topic-actions-block">
    {% include "forum_conversation/partials/topic_detail_actions.html" %}
  </div>
  <div class="col-12 col-md-8">
    {% with "pagination-sm justify-content-end" as pagination_size %}
    {% include "partials/pagination.html" %}
    {% endwith %}
  </div>
</div>
{% endblock content %}

machina/templates/machina/forum_conversation/topic_pages_inline_list.html
{% load i18n %}

{% if first_pages %}
&#91;&nbsp;
{% trans "Go to the page:" %}&nbsp;
{% for page in first_pages %}
<a href="{% url 'forum_conversation:topic' topic.forum.slug topic.forum.id topic.slug topic.pk %}?page={{ page }}">{{ page }}</a>{% if not forloop.last %}&#44;&nbsp;{% elif forloop.last and last_page %}&#44;&nbsp;{% endif %}
{% endfor %}
{% if last_page %}
&#133;&#44;&nbsp;<a href="{% url 'forum_conversation:topic' topic.forum.slug topic.forum.id topic.slug topic.pk %}?page={{ last_page }}">{{ last_page }}</a>
{% endif %}
&nbsp;&#93;
{% endif %}