machina/apps/forum/urls.py
"""
    Forum URLs
    ==========

    This module defines URL patterns associated with the django-machina's ``forum`` application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum`` application. """

    app_namespace = 'forum'

    index_view = get_class('forum.views', 'IndexView')
    forum_view = get_class('forum.views', 'ForumView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path('', self.index_view.as_view(), name='index'),
            path(
                'forum/<str:slug>-<int:pk>/',
                self.forum_view.as_view(),
                name='forum',
            ),
        ]


urlpatterns_factory = ForumURLPatternsFactory()

machina/apps/forum_conversation/urls.py
"""
    Forum conversation URLs
    =======================

    This module defines URL patterns associated with the django-machina's ``forum_conversation``
    application.

"""

from django.urls import include, path

from machina.apps.forum_conversation.forum_attachments.urls import \
    urlpatterns_factory as attachments_urlpatterns_factory
from machina.apps.forum_conversation.forum_polls.urls import \
    urlpatterns_factory as polls_urlpatterns_factory
from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class BaseForumConversationURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_conversation`` application. """

    app_namespace = 'forum_conversation'

    topic_view = get_class('forum_conversation.views', 'TopicView')
    topic_create_view = get_class('forum_conversation.views', 'TopicCreateView')
    topic_update_view = get_class('forum_conversation.views', 'TopicUpdateView')
    post_create_view = get_class('forum_conversation.views', 'PostCreateView')
    post_update_view = get_class('forum_conversation.views', 'PostUpdateView')
    post_delete_view = get_class('forum_conversation.views', 'PostDeleteView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        urlpatterns = super().get_urlpatterns()

        conversation_urlpatterns = [
            path(
                'topic/<str:slug>-<int:pk>/',
                self.topic_view.as_view(),
                name='topic',
            ),
            path('topic/create/', self.topic_create_view.as_view(), name='topic_create'),
            path(
                'topic/<str:slug>-<int:pk>/update/',
                self.topic_update_view.as_view(),
                name='topic_update',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/post/create/',
                self.post_create_view.as_view(),
                name='post_create',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/update/',
                self.post_update_view.as_view(),
                name='post_update',
            ),
            path(
                'topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/delete/',
                self.post_delete_view.as_view(),
                name='post_delete',
            ),
        ]

        urlpatterns += [
            path(
                'forum/<str:forum_slug>-<int:forum_pk>/',
                include(conversation_urlpatterns),
            ),
        ]

        return urlpatterns


class ForumAttachmentsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    attachments_urlpatterns_factory = attachments_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.attachments_urlpatterns_factory.urlpatterns)),
        ]


class ForumPollsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    polls_urlpatterns_factory = polls_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.polls_urlpatterns_factory.urlpatterns)),
        ]


class ForumConversationURLPatternsFactory(
    BaseForumConversationURLPatternsFactory, ForumAttachmentsURLPatternsFactory,
    ForumPollsURLPatternsFactory,
):
    """ Composite class combining conversation views with polls & attachments views. """


urlpatterns_factory = ForumConversationURLPatternsFactory()

machina/apps/forum_member/urls.py
"""
    Forum member URLs
    =================

    This module defines URL patterns associated with the django-machina's ``forum_member``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumMemberURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_member`` application. """

    app_namespace = 'forum_member'

    user_posts_list = get_class('forum_member.views', 'UserPostsView')
    forum_profile_detail_view = get_class('forum_member.views', 'ForumProfileDetailView')
    forum_profile_update_view = get_class('forum_member.views', 'ForumProfileUpdateView')
    topic_subscribe_view = get_class('forum_member.views', 'TopicSubscribeView')
    topic_unsubscribe_view = get_class('forum_member.views', 'TopicUnsubscribeView')
    topic_subscription_list_view = get_class('forum_member.views', 'TopicSubscriptionListView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'profile/edit/',
                self.forum_profile_update_view.as_view(),
                name='profile_update',
            ),
            path(
                'profile/<str:pk>/',
                self.forum_profile_detail_view.as_view(),
                name='profile',
            ),
            path(
                'profile/<str:pk>/posts/',
                self.user_posts_list.as_view(),
                name='user_posts',
            ),
            path(
                'subscriptions/',
                self.topic_subscription_list_view.as_view(),
                name='user_subscriptions',
            ),
            path(
                'topic/<int:pk>/subscribe/',
                self.topic_subscribe_view.as_view(),
                name='topic_subscribe',
            ),
            path(
                'topic/<int:pk>/unsubscribe/',
                self.topic_unsubscribe_view.as_view(),
                name='topic_unsubscribe',
            ),
        ]


urlpatterns_factory = ForumMemberURLPatternsFactory()

machina/apps/forum_moderation/urls.py
"""
    Forum moderation URLs
    =====================

    This module defines URL patterns associated with the django-machina's ``forum_moderation``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumModerationURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_moderation`` application. """

    app_namespace = 'forum_moderation'

    topic_lock_view = get_class('forum_moderation.views', 'TopicLockView')
    topic_unlock_view = get_class('forum_moderation.views', 'TopicUnlockView')
    topic_delete_view = get_class('forum_moderation.views', 'TopicDeleteView')
    topic_move_view = get_class('forum_moderation.views', 'TopicMoveView')
    topic_update_to_normal_topic_view = get_class(
        'forum_moderation.views', 'TopicUpdateToNormalTopicView',
    )
    topic_update_to_sticky_topic_view = get_class(
        'forum_moderation.views', 'TopicUpdateToStickyTopicView',
    )
    topic_update_to_announce_view = get_class('forum_moderation.views', 'TopicUpdateToAnnounceView')
    moderation_queue_list_view = get_class('forum_moderation.views', 'ModerationQueueListView')
    moderation_queue_detail_view = get_class('forum_moderation.views', 'ModerationQueueDetailView')
    post_approve_view = get_class('forum_moderation.views', 'PostApproveView')
    post_disapprove_view = get_class('forum_moderation.views', 'PostDisapproveView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'topic/<str:slug>-<int:pk>/lock/',
                self.topic_lock_view.as_view(),
                name='topic_lock',
            ),
            path(
                'topic/<str:slug>-<int:pk>/unlock/',
                self.topic_unlock_view.as_view(),
                name='topic_unlock',
            ),
            path(
                'topic/<str:slug>-<int:pk>/delete/',
                self.topic_delete_view.as_view(),
                name='topic_delete',
            ),
            path(
                'topic/<str:slug>-<int:pk>/move/',
                self.topic_move_view.as_view(),
                name='topic_move',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/topic/',
                self.topic_update_to_normal_topic_view.as_view(),
                name='topic_update_to_post',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/sticky/',
                self.topic_update_to_sticky_topic_view.as_view(),
                name='topic_update_to_sticky',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/announce/',
                self.topic_update_to_announce_view.as_view(),
                name='topic_update_to_announce',
            ),
            path('queue/', self.moderation_queue_list_view.as_view(), name='queue'),
            path(
                'queue/<int:pk>/',
                self.moderation_queue_detail_view.as_view(),
                name='queued_post',
            ),
            path(
                'queue/<int:pk>/approve/',
                self.post_approve_view.as_view(),
                name='approve_queued_post',
            ),
            path(
                'queue/<int:pk>/disapprove/',
                self.post_disapprove_view.as_view(),
                name='disapprove_queued_post',
            ),
        ]


urlpatterns_factory = ForumModerationURLPatternsFactory()

machina/urls.py
"""
    Machina URLs
    ============

    This module imports all the URLs defined by the forum-related applications.

"""

from django.conf.urls import include, url

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class BoardURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the whole forum application. """

    forum_urlpatterns_factory = get_class('forum.urls', 'urlpatterns_factory')
    conversation_urlpatterns_factory = get_class('forum_conversation.urls', 'urlpatterns_factory')
    feeds_urlpatterns_factory = get_class('forum_feeds.urls', 'urlpatterns_factory')
    member_urlpatterns_factory = get_class('forum_member.urls', 'urlpatterns_factory')
    moderation_urlpatterns_factory = get_class('forum_moderation.urls', 'urlpatterns_factory')
    search_urlpatterns_factory = get_class('forum_search.urls', 'urlpatterns_factory')
    tracking_urlpatterns_factory = get_class('forum_tracking.urls', 'urlpatterns_factory')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            url(r'', include(self.forum_urlpatterns_factory.urlpatterns)),
            url(r'', include(self.conversation_urlpatterns_factory.urlpatterns)),
            url(r'^feeds/', include(self.feeds_urlpatterns_factory.urlpatterns)),
            url(r'^member/', include(self.member_urlpatterns_factory.urlpatterns)),
            url(r'^moderation/', include(self.moderation_urlpatterns_factory.urlpatterns)),
            url(r'^search/', include(self.search_urlpatterns_factory.urlpatterns)),
            url(r'^tracking/', include(self.tracking_urlpatterns_factory.urlpatterns)),
        ]


urlpatterns_factory = BoardURLPatternsFactory()
urlpatterns = urlpatterns_factory.get_urlpatterns()

machina/apps/forum_moderation/forms.py
"""
    Forum moderation forms
    ======================

    This module defines forms provided by the ``forum_moderation`` application.

"""

from django import forms
from django.utils.translation import gettext_lazy as _

from machina.core.db.models import get_model
from machina.core.loading import get_class
from machina.forms.widgets import SelectWithDisabled


Forum = get_model('forum', 'Forum')

PermissionHandler = get_class('forum_permission.handler', 'PermissionHandler')


class TopicMoveForm(forms.Form):
    """ Allows to move a topic. """

    forum = forms.ChoiceField(label=_('Select a destination forum'), widget=SelectWithDisabled)
    lock_topic = forms.BooleanField(label=_('Lock topic'), required=False)

    def __init__(self, *args, **kwargs):
        self.topic = kwargs.pop('topic', None)
        self.user = kwargs.pop('user', None)
        self.perm_handler = PermissionHandler()

        super().__init__(*args, **kwargs)

        self.allowed_forums = self.perm_handler.get_target_forums_for_moved_topics(self.user)
        forum_choices = []

        for f in self.allowed_forums:
            if f.is_category or f.id == self.topic.forum.id:
                forum_choices.append((
                    f.id,
                    {
                        'label': '{} {}'.format('-' * f.margin_level, f.name),
                        'disabled': True,
                    }
                ))
            else:
                forum_choices.append((f.id, '{} {}'.format('-' * f.margin_level, f.name)))

        if self.topic.is_locked:
            self.fields['lock_topic'].initial = True

        self.fields['forum'].choices = forum_choices

    def clean_forum(self):
        forum_id = self.cleaned_data['forum']

        if forum_id:
            forum = Forum.objects.get(pk=forum_id)
            if forum.is_category or forum.is_link or forum.id == self.topic.forum.id:
                raise forms.ValidationError('You cannot select this forum as a destination')

        return forum

machina/templates/machina/forum_moderation/moderation_queue/detail.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_member_tags %}

{% block sub_title %}{% trans "Moderation queue" %}{% endblock sub_title %}

{% block content %}
<div class="row">
  <div class="col-12">
    <h1>{% trans "Moderation queue" %}</h1>
  </div>
</div>
<div class="alert alert-warning" role="alert">
  <div class="float-right">
    <a href="{% url 'forum_moderation:disapprove_queued_post' post.pk %}" class="btn btn-warning">{% trans "Disapprove" %}</a>
    <a href="{% url 'forum_moderation:approve_queued_post' post.pk %}" class="btn btn-success"><b>{% trans "Approve" %}</b></a>
  </div>
  <h4>{{ post.subject }}</h4>
  <p class="text-muted">{% if post.is_topic_head %}{% trans "New topic" %}{% else %}{% trans "New post" %}{% endif %}</p>
</div>
<div class="my-3 row">
  <div class="col-12">
    {% if post.is_topic_head and poll %}
    <div class="mb-3 card poll">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12 poll-content-wrapper">
            <h4 class="question">{{ poll.question }}</h4>
            <hr />
            <div class="max-options-indication">
              {% if poll.max_options == 1 %}
              {% blocktrans trimmed %}
              <b>1</b> option may be selected
              {% endblocktrans %}
              {% else %}
              {% blocktrans trimmed with max_options=poll.max_options %}
              Up to <b>{{ max_options }}</b> options may be selected
              {% endblocktrans %}
              {% endif %}
            </div>
            <div class="poll-options">
            {% for option in poll_options %}
            {% if forloop.first or not forloop.counter|divisibleby:2 %}
            <div class="row">
            {% endif %}
            <div class="col-md-6">
              <div class="well well-sm">
                {% if poll.max_options == 1 %}
                <div class="radio">
                  <label>
                    <input type="radio" name="options" value="{{ option.id }}">
                    {{ option.text }}
                  </label>
                </div>
                {% else %}
                <div class="checkbox">
                  <label>
                    <input type="checkbox" name="options" value="{{ option.id }}">
                    {{ option.text }}
                  </label>
                </div>
                {% endif %}
              </div>
            </div>
            {% if forloop.last or forloop.counter|divisibleby:2 %}
            </div>
            {% endif %}
            {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
    <div id="{{ post.id }}" class="card post">
      <div class="card-body">
        <div class="row">
          <div class="col-md-10 post-content-wrapper">
            <h4 class="subject">{{ post.subject }}</h4>
            <p>
              <small class="text-muted">
                {% spaceless %}
                <i class="fas fa-clock"></i>&nbsp;
                {% if post.poster %}
                {% url 'forum_member:profile' post.poster_id as poster_url %}
                {% blocktrans trimmed with poster_url=poster_url username=post.poster|forum_member_display_name creation_date=post.created %}
                By: <a href="{{ poster_url }}">{{ username }}</a> on {{ creation_date }}
                {% endblocktrans %}
                {% else %}
                {% blocktrans trimmed with poster_username=post.username creation_date=post.created %}
                By: {{ poster_username }} on {{ creation_date }}
                {% endblocktrans %}
                {% endif %}
                {% endspaceless %}
              </small>
            </p>
            <div class="post-content">
              {{ post.content.rendered }}
            </div>
            {% include "forum_conversation/forum_attachments/attachments_detail.html" %}
            {% if post.enable_signature and post.poster.forum_profile.signature %}
            <div class="post-signature">
              {{ post.poster.forum_profile.signature.rendered }}
            </div>
            {% endif %}
          </div>
          <div class="col-md-2 post-sidebar">
            {% if post.poster %}
            {% if post.poster.forum_profile.avatar %}
            <div class="avatar">
              <a href="{% url 'forum_member:profile' post.poster_id %}">
                {% include "partials/avatar.html" with profile=post.poster.forum_profile placeholder=False %}
              </a>
            </div>
            {% endif %}
            <div class="username"><a href="{% url 'forum_member:profile' post.poster_id %}"><b>{{ post.poster|forum_member_display_name }}</b></a></div>
            <div class="posts-count text-muted"><b>{% trans "Posts:" %}</b>&nbsp;{{ post.poster.forum_profile.posts_count }}</div>
            {% else %}
            <div class="username"><b>{{ post.username }}</b></div>
            <div class="username text-muted">{% trans "Anonymous user" %}</div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% if previous_posts %}
<div class="row">
  <div class="col-12">
    <div class="card topic-review">
      <div class="card-header">
        <h3 class="m-0 h5 card-title">{% trans "Topic review" %}&nbsp;&ndash;&nbsp;{{ post.topic.subject }}</h3>
      </div>
      <div class="card-body">
        {% for post in previous_posts %}
        <div class="row post-review">
          <div class="col-md-10 post-content-wrapper">
            <h4 class="subject">{{ post.subject }}</h4>
            <p><small class="text-muted">
            {% spaceless %}
            <i class="fas fa-clock"></i>&nbsp;
            {% if post.poster %}
            {% url 'forum_member:profile' post.poster_id as poster_url %}
            {% blocktrans trimmed with poster_url=poster_url username=post.poster|forum_member_display_name creation_date=post.created %}
            By: <a href="{{ poster_url }}">{{ username }}</a> on {{ creation_date }}
            {% endblocktrans %}
            {% else %}
            {% blocktrans trimmed with poster_username=post.username creation_date=post.created %}
            By: {{ poster_username }} on {{ creation_date }}
            {% endblocktrans %}
            {% endif %}
            {% endspaceless %}
            </small></p>
            <div class="post-content">
              {{ post.content.rendered }}
            </div>
            {% include "forum_conversation/forum_attachments/attachments_detail.html" %}
          </div>
          <div class="col-md-2 post-sidebar">
            <div class="username">{% if post.poster %}<a href="{% url 'forum_member:profile' post.poster_id %}"><b>{{ post.poster|forum_member_display_name }}</b></a>{% else %}<b>{{ post.username }}</b>{% endif %}</div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}

machina/templates/machina/forum_moderation/moderation_queue/list.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_member_tags %}

{% block sub_title %}{% trans "Moderation queue" %}{% endblock sub_title %}

{% block content %}
<div class="row">
  <div class="col-12">
    <h1>{% trans "Moderation queue" %}</h1>
  </div>
</div>
<div class="mb-3 row">
  <div class="col-6 col-md-4 forum-actions-block">
    {% if paginator.count > 0 %}
    <p class="mt-1 mb-0 text-muted">
      {% blocktrans with paginator.count as topic_length %}{{ topic_length }} posts found{% endblocktrans %}
    </p>
    {% endif %}
  </div>
  <div class="col-12 col-md-8 pagination-block">
    {% with "pagination-sm justify-content-end" as pagination_size %}
    {% include "partials/pagination.html" %}
    {% endwith %}
  </div>
</div>
<div class="row">
  <div class="col-12">
    <div class="card postmoderationlist">
      <div class="card-header">
        <div class="row panel-row">
          <div class="col-12 col-md-8 post-name-col">
            <h3 class="m-0 card-title h5">{% trans "Moderation queue" %}</h3>
          </div>
          <div class="col-md-2 d-none d-md-block moderation-col">{% trans "Topic" %}</div>
          <div class="col-md-2 d-none d-md-block moderation-col">{% trans "Forum" %}</div>
        </div>
      </div>
      <div class="p-0 card-body">
        {% for post in posts %}
        <div class="m-0 row">
          <div class="col-12 col-md-8 post-name">
            <table class="post-data-table">
              <tr>
                <td class="post-name">
                  <a href="{% url 'forum_moderation:queued_post' post.pk %}" class="post-name-link">{{ post.subject }}</a>
                  <div>
                    <div class="post-created">
                      {% if post.poster %}
                      {% url 'forum_member:profile' post.poster_id as poster_url %}
                      {% blocktrans trimmed with poster_url=poster_url username=post.poster|forum_member_display_name creation_date=post.created %}
                      By: <a href="{{ poster_url }}">{{ username }}</a> on {{ creation_date }}
                      {% endblocktrans %}
                      {% else %}
                      {% blocktrans trimmed with poster_username=post.username creation_date=post.created %}
                      By: {{ poster_username }} on {{ creation_date }}
                      {% endblocktrans %}
                      {% endif %}
                    </div>
                  </div>
                </td>
              </tr>
            </table>
          </div>
          <div class="col-md-2 d-none d-md-block topic-name">
            {% if post.is_topic_head %}
            <span class="badge badge-secondary">{% trans "New topic" %}</span>
            {% else %}
            <a href="{% url 'forum_conversation:topic' forum_slug=post.topic.forum.slug forum_pk=post.topic.forum.pk slug=post.topic.slug pk=post.topic.pk %}" class="post-name-link">{{ post.topic.subject }}</a>
            {% endif %}
          </div>
          <div class="col-md-2 d-none d-md-block forum-name">
            <a href="{% url 'forum:forum' slug=post.topic.forum.slug pk=post.topic.forum.pk %}" class="post-name-link">{{ post.topic.forum.name }}</a>
          </div>
        </div>
        {% empty %}
        <div class="row m-0 px-3 py-2">
          <div class="p-0 col-12">
            {% trans "No posts awaiting approval." %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12 pagination-block">
    {% with "pagination-sm justify-content-end" as pagination_size %}
    {% include "partials/pagination.html" %}
    {% endwith %}
  </div>
</div>
{% endblock content %}

machina/templates/machina/forum_moderation/moderation_queue/post_approve.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_conversation_tags %}

{% block sub_title %}{% trans "Approve post" %}{% endblock sub_title %}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card topic-lock">
      <div class="card-header">
        <h3 class="m-0 card-title h5">{% trans "Approve post" %}</h3>
      </div>
      <div class="card-body">
        <div class="mb-3 warning-message">{% trans "Are you sure you want to approve this post?" %}</div>
        <form action="" method="post">{% csrf_token %}
          <input type="hidden" name="post" value="yes" />
          <button role="submit" class="btn btn-warning">{% trans "Yes, I'm sure" %}</button>
          <a href="{% url 'forum_moderation:queued_post' post.pk %}" class="btn btn-secondary">{% trans "No, take me back" %}</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

machina/templates/machina/forum_moderation/moderation_queue/post_disapprove.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_conversation_tags %}

{% block sub_title %}{% trans "Disapprove post" %}{% endblock sub_title %}

{% block content %}
<div class="row">
  <div class="col-12">
  <div class="card topic-lock">
  <div class=card-header>
    <h3 class="m-0 card-title h5">{% trans "Disapprove post" %}</h3>
  </div>
  <div class="card-body">
    <div class="mb-3 warning-message">{% trans "Are you sure you want to disapprove this post? This post will be deleted." %}</div>
    <form action="" method="post">{% csrf_token %}
      <input type="hidden" name="post" value="yes" />
      <button role="submit" class="btn btn-warning">{% trans "Yes, I'm sure" %}</button>
      <a href="{% url 'forum_moderation:queued_post' post.pk %}" class="btn btn-secondary">{% trans "No, take me back" %}</a>
    </form>
  </div>
  </div>
  </div>
</div>
{% endblock content %}