machina/apps/forum/urls.py
"""
    Forum URLs
    ==========

    This module defines URL patterns associated with the django-machina's ``forum`` application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum`` application. """

    app_namespace = 'forum'

    index_view = get_class('forum.views', 'IndexView')
    forum_view = get_class('forum.views', 'ForumView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path('', self.index_view.as_view(), name='index'),
            path(
                'forum/<str:slug>-<int:pk>/',
                self.forum_view.as_view(),
                name='forum',
            ),
        ]


urlpatterns_factory = ForumURLPatternsFactory()

machina/apps/forum_member/urls.py
"""
    Forum member URLs
    =================

    This module defines URL patterns associated with the django-machina's ``forum_member``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumMemberURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_member`` application. """

    app_namespace = 'forum_member'

    user_posts_list = get_class('forum_member.views', 'UserPostsView')
    forum_profile_detail_view = get_class('forum_member.views', 'ForumProfileDetailView')
    forum_profile_update_view = get_class('forum_member.views', 'ForumProfileUpdateView')
    topic_subscribe_view = get_class('forum_member.views', 'TopicSubscribeView')
    topic_unsubscribe_view = get_class('forum_member.views', 'TopicUnsubscribeView')
    topic_subscription_list_view = get_class('forum_member.views', 'TopicSubscriptionListView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'profile/edit/',
                self.forum_profile_update_view.as_view(),
                name='profile_update',
            ),
            path(
                'profile/<str:pk>/',
                self.forum_profile_detail_view.as_view(),
                name='profile',
            ),
            path(
                'profile/<str:pk>/posts/',
                self.user_posts_list.as_view(),
                name='user_posts',
            ),
            path(
                'subscriptions/',
                self.topic_subscription_list_view.as_view(),
                name='user_subscriptions',
            ),
            path(
                'topic/<int:pk>/subscribe/',
                self.topic_subscribe_view.as_view(),
                name='topic_subscribe',
            ),
            path(
                'topic/<int:pk>/unsubscribe/',
                self.topic_unsubscribe_view.as_view(),
                name='topic_unsubscribe',
            ),
        ]


urlpatterns_factory = ForumMemberURLPatternsFactory()

machina/apps/forum_moderation/urls.py
"""
    Forum moderation URLs
    =====================

    This module defines URL patterns associated with the django-machina's ``forum_moderation``
    application.

"""

from django.urls import path

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumModerationURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_moderation`` application. """

    app_namespace = 'forum_moderation'

    topic_lock_view = get_class('forum_moderation.views', 'TopicLockView')
    topic_unlock_view = get_class('forum_moderation.views', 'TopicUnlockView')
    topic_delete_view = get_class('forum_moderation.views', 'TopicDeleteView')
    topic_move_view = get_class('forum_moderation.views', 'TopicMoveView')
    topic_update_to_normal_topic_view = get_class(
        'forum_moderation.views', 'TopicUpdateToNormalTopicView',
    )
    topic_update_to_sticky_topic_view = get_class(
        'forum_moderation.views', 'TopicUpdateToStickyTopicView',
    )
    topic_update_to_announce_view = get_class('forum_moderation.views', 'TopicUpdateToAnnounceView')
    moderation_queue_list_view = get_class('forum_moderation.views', 'ModerationQueueListView')
    moderation_queue_detail_view = get_class('forum_moderation.views', 'ModerationQueueDetailView')
    post_approve_view = get_class('forum_moderation.views', 'PostApproveView')
    post_disapprove_view = get_class('forum_moderation.views', 'PostDisapproveView')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'topic/<str:slug>-<int:pk>/lock/',
                self.topic_lock_view.as_view(),
                name='topic_lock',
            ),
            path(
                'topic/<str:slug>-<int:pk>/unlock/',
                self.topic_unlock_view.as_view(),
                name='topic_unlock',
            ),
            path(
                'topic/<str:slug>-<int:pk>/delete/',
                self.topic_delete_view.as_view(),
                name='topic_delete',
            ),
            path(
                'topic/<str:slug>-<int:pk>/move/',
                self.topic_move_view.as_view(),
                name='topic_move',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/topic/',
                self.topic_update_to_normal_topic_view.as_view(),
                name='topic_update_to_post',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/sticky/',
                self.topic_update_to_sticky_topic_view.as_view(),
                name='topic_update_to_sticky',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/announce/',
                self.topic_update_to_announce_view.as_view(),
                name='topic_update_to_announce',
            ),
            path('queue/', self.moderation_queue_list_view.as_view(), name='queue'),
            path(
                'queue/<int:pk>/',
                self.moderation_queue_detail_view.as_view(),
                name='queued_post',
            ),
            path(
                'queue/<int:pk>/approve/',
                self.post_approve_view.as_view(),
                name='approve_queued_post',
            ),
            path(
                'queue/<int:pk>/disapprove/',
                self.post_disapprove_view.as_view(),
                name='disapprove_queued_post',
            ),
        ]


urlpatterns_factory = ForumModerationURLPatternsFactory()

machina/apps/forum_search/urls.py
"""
    Forum search URLs
    =================

    This module defines URL patterns associated with the django-machina's ``forum_search``
    application.

"""

from django.urls import path
from haystack.views import search_view_factory

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class ForumSearchURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_search`` application. """

    app_namespace = 'forum_search'

    search_view = get_class('forum_search.views', 'FacetedSearchView')
    search_form = get_class('forum_search.forms', 'SearchForm')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                '',
                search_view_factory(view_class=self.search_view, form_class=self.search_form),
                name='search',
            ),
        ]


urlpatterns_factory = ForumSearchURLPatternsFactory()

machina/urls.py
"""
    Machina URLs
    ============

    This module imports all the URLs defined by the forum-related applications.

"""

from django.conf.urls import include, url

from machina.core.loading import get_class
from machina.core.urls import URLPatternsFactory


class BoardURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the whole forum application. """

    forum_urlpatterns_factory = get_class('forum.urls', 'urlpatterns_factory')
    conversation_urlpatterns_factory = get_class('forum_conversation.urls', 'urlpatterns_factory')
    feeds_urlpatterns_factory = get_class('forum_feeds.urls', 'urlpatterns_factory')
    member_urlpatterns_factory = get_class('forum_member.urls', 'urlpatterns_factory')
    moderation_urlpatterns_factory = get_class('forum_moderation.urls', 'urlpatterns_factory')
    search_urlpatterns_factory = get_class('forum_search.urls', 'urlpatterns_factory')
    tracking_urlpatterns_factory = get_class('forum_tracking.urls', 'urlpatterns_factory')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            url(r'', include(self.forum_urlpatterns_factory.urlpatterns)),
            url(r'', include(self.conversation_urlpatterns_factory.urlpatterns)),
            url(r'^feeds/', include(self.feeds_urlpatterns_factory.urlpatterns)),
            url(r'^member/', include(self.member_urlpatterns_factory.urlpatterns)),
            url(r'^moderation/', include(self.moderation_urlpatterns_factory.urlpatterns)),
            url(r'^search/', include(self.search_urlpatterns_factory.urlpatterns)),
            url(r'^tracking/', include(self.tracking_urlpatterns_factory.urlpatterns)),
        ]


urlpatterns_factory = BoardURLPatternsFactory()
urlpatterns = urlpatterns_factory.get_urlpatterns()

machina/templates/machina/_base.html
{% load i18n %}

<!DOCTYPE html>
<html {% get_current_language as LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}">
  <head>
    {% block head %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>

    <title>{% block title %}{{ site.name }}{% endblock %}</title>
    <meta name="created" content="{% now "jS M Y h:i" %}" />
    <meta name="description" content="{% block meta_description %}{% endblock meta_description %}" />
    <meta name="keywords" content="{% block meta_keywords %}{% endblock meta_keywords %}"/>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% endblock head %}

    {% block css %}
    {% endblock css %}

    {% block extra_css %}
    {% endblock extra_css %}

  </head>
  <body>
    {% block js %}
    {% endblock js %}

    {% block body %}
      {# The forum content will go in this 'body' block #}
    {% endblock body %}

    {% block extra_js %}
    {% endblock extra_js %}
  </body>
</html>

machina/templates/machina/board_base.html
{% extends MACHINA_BASE_TEMPLATE_NAME %}
{% load static %}
{% load i18n %}
{% load forum_permission_tags %}

{% block title %}{{ MACHINA_FORUM_NAME|default:"Forum" }} &mdash; {% block sub_title %}{% endblock sub_title %}{% endblock title %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/machina.board_theme.vendor.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/machina.board_theme.min.css' %}" />
{% endblock css %}

{% block body %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'forum:index' %}">{% block brand %}{{ MACHINA_FORUM_NAME|default:"My forum" }}{% endblock %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% block header_collapse %}
    <form class="form-inline my-2 ml-3 my-lg-0" role="search" action="{% url 'forum_search:search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
    </form>
    <div class="navbar-nav mr-auto">
      <a class="nav-item nav-link" href="{% url 'forum_search:search' %}">{% trans "Advanced search" %}</a>
    </div>
    {% endblock header_collapse %}
  </div>
</nav>
{% endblock header %}
<div class="my-5 container" id="main_container">
  <div class="row">
    <div class="col-12">
      {% block breadcrumb %}{% include "partials/breadcrumb.html" %}{% endblock breadcrumb %}
      <div class="float-right controls-link-wrapper">
      {% spaceless %}
      {% if not request.user.is_anonymous %}
        <a href="{% url 'forum_member:user_subscriptions' %}" class="d-inline-block ml-3"><i class="fas fa-bookmark">&nbsp;</i>{% trans "Subscriptions" %}</a>
        <a href="{% url 'forum_member:user_posts' request.user.id %}" class="d-inline-block ml-3"><i class="fas fa-comments">&nbsp;</i>{% trans "View my posts" %}</a>
      {% endif %}
      {% get_permission 'can_access_moderation_queue' request.user as can_access_moderation_queue %}
      {% if can_access_moderation_queue %}
        <a href="{% url 'forum_moderation:queue' %}" class="d-inline-block ml-3"><i class="fas fa-gavel">&nbsp;</i>{% trans "Moderation queue" %}</a>
      {% endif %}
      {% endspaceless %}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <br />
      {% block messages %}{% include "partials/messages.html" %}{% endblock messages %}
    </div>
  </div>
  {% block content %}
  {% endblock content %}
</div>
{% endblock body %}

{% block js %}
{{ block.super }}
<script src="{% static 'js/machina.packages.min.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'js/machina.min.js' %}" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
  $(function() {
    machina.init();
    {% block onbodyload %}{% endblock onbodyload %}
  });
</script>
{% endblock js %}